import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillGithub,
  AiFillLinkedin,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../../public/dev-ed-wave.png";
import design from "../../public/design.png";
import code from "../../public/code.png";
import consulting from "../../public/consulting.png";
import web1 from "../../public/web1.png";
import web2 from "../../public/web2.png";
import web3 from "../../public/web3.png";
import web4 from "../../public/web4.png";
import web5 from "../../public/web5.png";
import web6 from "../../public/web6.png";
import Nav from "@/components/Nav";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Andreyhuey Portfolio</title>
        <meta name="description" content="Generated by " />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:text-white">
        {/* Hero & Nav Section */}
        <section className=" min-h-screen mb-2">
          <Nav />
          <div className="text-center p-10 dark:text-white">
            <h2 className="text-5xl py-2 text-teal-600 dark:text-teal-600 font-medium md:text-6xl ">
              Andreyhuey
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">Front-End Developer</h3>
            <p className="text-md py-5 leading-8 text-grey-800 md:text-xl max-w-xl mx-auto">
              Freelancer providing services for web development i.e web app
              designing, API development and BaaS i.e backend as a Service e.g
              Firebase.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="https://twitter.com/Andreyhuey" target="_blank">
              <AiFillTwitterCircle />
            </a>
            <a
              href="https://www.linkedin.com/in/oluwadara-ola-obaado-64b5511b4/"
              target="_blank"
            >
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/Andreyhuey" target="_blank">
              <AiFillGithub />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} style={{ objectFit: "cover" }} fill />
          </div>
        </section>
        {/* Services Section */}
        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              Since my journey as a developer i have lorem ipsum lorem ipsum
              lorem ipsum, lorem ipsum lorem ipsum lorem ipsum lorem ipsum,
              lorem ipsum
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups</span>{" "}
              lorem ipsum lorem ipsum lorem ipsum lorem ipsum,
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              I offer from a wide range of services, including brainstorming and
              programming, teaching and so on
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-800">
              <Image
                src={design}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-meduim pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p> Creating elegant desgins suited for your need ...</p>
              <h4 className="py-4 text-teal-600">Design tools i use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-300">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                Ilustrator
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-800">
              <Image
                src={consulting}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-meduim pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p> Creating elegant desgins suited for your needs</p>
              <h4 className="py-4 text-teal-600">Design tools i use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-300">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                Ilustrator
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-800">
              <Image src={code} width={100} height={100} className="mx-auto" />
              <h3 className="text-lg font-meduim pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p> Creating elegant desgins suited for your need ...</p>
              <h4 className="py-4 text-teal-600">Design tools i use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-300">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                Ilustrator
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">Figma</p>
            </div>
          </div>
        </section>
        {/* Portfolio Section */}
        <section>
          <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              Since my journey as a developer i have lorem ipsum lorem ipsum
              lorem ipsum, i have freelanced various websites and have managed
              various facilities
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">
                {" "}
                startups{" "}
              </span>{" "}
              and collaborated with talanted people to
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              I offer from a wide range of services, including brainstorming and
              programming, teaching and so on
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/4 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                style={{ layout: "responsive" }}
              />
            </div>
            <div className="basis-1/4 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                style={{ layout: "responsive" }}
              />
            </div>
            <div className="basis-1/4 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                style={{ layout: "responsive" }}
              />
            </div>
            <div className="basis-1/4 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                style={{ layout: "responsive" }}
              />
            </div>
            <div className="basis-1/4 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                style={{ layout: "responsive" }}
              />
            </div>
            <div className="basis-1/4 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                style={{ layout: "responsive" }}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
